### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by IKGapirov** [andi34/android_asb#1]
Good day!
I'm sorry for disturbing you
I wanted to update, but I get an error
`ikgapirov@android:~/ANDROID/asb/asb-2018-04/build$ repo forall -c "git am 0001-Bump-security-patch-level-to-2018-04-05.patch"
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
предыдущий каталог перемещения /home/ikgapirov/ANDROID/RR-N/build/.git/rebase-apply еще существует, но передан mbox.
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file
предыдущий каталог перемещения /home/ikgapirov/ANDROID/RR-N/device/common/.git/rebase-apply еще существует, но передан mbox.
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open 0001-Bump-security-patch-level-to-2018-04-05.patch: No such file`
What am I doing wrong
Please can u advise something about this
Thank you in advance!

**Comment by andi34** [comment]
Copy and past the patches into the needed repos. After that run

repo forall -c "git am *.patch"

Atm you are trying to apply the same patch on every repo. Lol.

**Comment by IKGapirov** [comment]
#Verry sorry...
I do what u say ---> Copy and past the patches into the needed repos.
And After that run ---> repo forall -c "git am *.patch"
And instead "*", what should I put something?
Get...
`ikgapirov@android:~/ANDROID$ repo forall -c "git am *.patch"
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
предыдущий каталог перемещения /home/ikgapirov/ANDROID/RR-N/build/.git/rebase-apply еще существует, но передан mbox.
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
предыдущий каталог перемещения /home/ikgapirov/ANDROID/RR-N/device/common/.git/rebase-apply еще существует, но передан mbox.
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file
/usr/lib/git-core/git-am: 209: /usr/lib/git-core/git-am: cannot open *.patch: No such file`

**Comment by andi34** [comment]
https://youtu.be/xv5Eb1SL96E

**Comment by IKGapirov** [comment]
Thank u!
