### ISSUE TITLE
Android_asb for Oreo

### ISSUE THREAD

**Issue by IKGapirov** [andi34/android_asb#2]
Good day!
Sorry to bother you. Thank u for your hard work.
Please can you advise where I can get it for 8.1?
Thank you in advance!

**Comment by andi34** [comment]
You can check https://github.com/novoda/aosp.changelog.to to generate your own changelog between last months and new months tag for oreo, you can grab the changes from there.

You can also check https://source.android.com/security/bulletin/2018

**Comment by IKGapirov** [comment]
Thanks for answering.
Sorry, and you don`t have a video, how did you all do it?

пт, 21 сент. 2018 г. в 17:16, Andreas Blaesius <notifications@github.com>:

**Comment by andi34** [comment]
No and I don't have time for it. Follow the instructions to generate the changelog, after that you can cherry-pick needed changes on top of your source. To create the patch file run:
"git format-patch -COUNT"

E.g. "git format-patch -1" to generate the patch file for latest commit applied. For last 2 commits -2 for last 30 commits -30 and so on.

**Comment by IKGapirov** [comment]
Understood thanks!

пт, 21 сент. 2018 г. в 18:30, Andreas Blaesius <notifications@github.com>:
